this_tuple=("cars",123,"jeeps",1.2,1.2,('a',"b",18),[1,2,3,4])
# print(len(this_tuple))
# print((this_tuple))
# print(type(this_tuple))
# print(this_tuple[:-1])
# print((this_tuple[::-2]))
# #print(max(this_tuple))#type error
# t=(1,2,15,3,4)
# print(max(t))
# print(len(t))
# #print(sort(t))
# t2=()
# list1=list(this_tuple)
# print(list1)
# list1.remove("jeeps")
# print(list1)
# this_tuple=tuple(list1)
# print(this_tuple)
#to relace in tple
list1=list(this_tuple)
str1=str(this_tuple)
print(str1)
list1.remove("jeeps")
print(list1)